// catalogData.ts
// Catálogo de sectores económicos y sus profesiones asociadas

export const SECTORES_ECONOMICOS = [
    "COMERCIO",
    "SERVICIO",
    "PRODUCCION AGRICOLA",
    "PRODUCCION PECUARIO",
    "PRODUCCION INDUSTRIAL Y ARTESANAL",
    "PROFESIONALES"
] as const;

export type SectorEconomico = typeof SECTORES_ECONOMICOS[number];

export const PROFESIONES_POR_SECTOR: Record<SectorEconomico, string[]> = {
    "COMERCIO": [
        "ADMINISTRADORA DE TIENDA",
        "AGRICULTORES",
        "ALBAÑIL",
        "AMA DE CASA",
        "ANALISTAS DE SISTEMAS",
        "ARTESANO",
        "ASESORES FINANCIEROS",
        "ASISTENTE",
        "AUDITOR",
        "BACHILLER EN COMPUTACION",
        "BARBERO",
        "CAMARERA",
        "CARNICERO",
        "CARPINTERO",
        "COCINERO",
        "COMADRONA",
        "COMERCIANTE",
        "COMISARIO",
        "CRIANZA DE AVES",
        "DEPENDIENTE",
        "ENCARGADO DE COMEDORES",
        "ENFERMERO",
        "ESTILISTA",
        "ESTUDIANTE",
        "GANADERO",
        "GRANJERO",
        "GUARDIA DE SEGURIDAD",
        "HERRERO",
        "JORNALERO",
        "LICENCIADO EN ADMON. EMPRESAS",
        "MECÁNICO",
        "MECÁNICOS Y REPARADORES DE MÁQ",
        "MEDICO",
        "MOLDEADORES, SOLDADORES",
        "OPERADOR DE MAQUINARIA",
        "PANADERO",
        "PESCADOR",
        "PILOTO",
        "POLICÍA MUNICIPAL DE TRANSITO",
        "PROFESORADO EN EDUCACION BIL",
        "SERVICIO AL CLIENTE",
        "SERVICIOS PROFESIONALES",
        "SUPERVISOR",
        "TEJEDORES",
        "TRANSPORTISTA",
        "VENDEDOR",
        "VENDEDORES AMBULANTES",
        "VENTA DE POLLOS",
        "VENTA DE ROPA",
        "VENTA POR CATALOGO",
        "VENTA PRODUCTOS POR CATALOGO"
    ],

    "SERVICIO": [
        "AGRICULTORES",
        "ALBAÑIL",
        "AMA DE CASA",
        "ANALISTAS DE GESTIÓN",
        "ARRENDAMIENTO DE INMUEBLES",
        "ASISTENTE",
        "AYUDANTE",
        "BACHILLER EN COMPUTACION",
        "BARBERO",
        "CAMARERA",
        "CARPINTERO",
        "COMERCIANTE",
        "CONTADOR",
        "COSTURERA",
        "CUADRILLERO",
        "DEPENDIENTE",
        "ELECTRICISTAS DE OBRAS",
        "ENFERMERA",
        "ENFERMERO",
        "ESTILISTA",
        "ESTUDIANTE",
        "FOTOGRAFO",
        "HERRERO",
        "JORNALERO",
        "LICENCIADO EN PEDAGOGIA",
        "MAESTRO DE ENSEÑANZA",
        "MAESTRO DE OBRA",
        "MECÁNICO",
        "MECÁNICOS Y REPARADORES DE MÁQ",
        "MEDICO",
        "MOLDEADORES, SOLDADORES",
        "PILOTO",
        "POLICÍA MUNICIPAL DE TRANSITO",
        "SASTRE",
        "SERVICIO AL CLIENTE",
        "SERVICIOS DE TRANSPORTE",
        "SERVICIOS PROFESIONALES",
        "SOLDADOR",
        "TÉCNICO",
        "TECNICO ELECTRICISTA",
        "TRANSPORTISTA",
        "VENDEDOR",
        "VENTA DE GAS PROPANO"
    ],

    "PRODUCCION AGRICOLA": [
        "AGRICULTORES",
        "ALBAÑIL",
        "AMA DE CASA",
        "COMERCIANTE",
        "HERRERO"
    ],

    "PRODUCCION PECUARIO": [
        "ADMINISTRADOR",
        "AGRICULTORES",
        "ALBAÑIL",
        "AMA DE CASA",
        "CARNICERO",
        "COMERCIANTE",
        "CRIANZA DE AVES",
        "GANADERO",
        "GRANJERO",
        "JORNALERO",
        "PEON",
        "PRODUCCION PECUARIO",
        "SERVICIO AL CLIENTE",
        "VENDEDOR",
        "VENTA DE GAS PROPANO",
        "VENTA DE POLLOS"
    ],

    "PRODUCCION INDUSTRIAL Y ARTESANAL": [
        "AGRICULTORES",
        "AMA DE CASA",
        "ARTESANO",
        "CARPINTERO",
        "COMERCIANTE",
        "COMISARIO",
        "EMPRESARIO",
        "HERRERO",
        "PANADERO",
        "RASPADOR DE MADERA",
        "SUPERVISOR",
        "TEJEDORES"
    ],

    "PROFESIONALES": [
        "ABOGADO",
        "ADMINISTRADOR DE EMPRESAS",
        "ANALISTA DE SISTEMAS",
        "ANALISTA FINANCIERO",
        "ARQUITECTO",
        "ASESOR FINANCIERO",
        "AUDITOR",
        "BIOLOGO",
        "CIRUJANO",
        "COMUNICADOR SOCIAL",
        "CONTADOR PUBLICO",
        "CONTADOR",
        "DENTISTA",
        "DISEÑADOR GRAFICO",
        "ECONOMISTA",
        "ENFERMERA PROFESIONAL",
        "ENFERMERO PROFESIONAL",
        "FARMACEUTICO",
        "FISIOTERAPEUTA",
        "INGENIERO AGRICOLA",
        "INGENIERO CIVIL",
        "INGENIERO DE SISTEMAS",
        "INGENIERO ELECTRONICO",
        "INGENIERO INDUSTRIAL",
        "INGENIERO MECANICO",
        "INGENIERO QUIMICO",
        "LICENCIADO EN ADMINISTRACION",
        "LICENCIADO EN COMUNICACION",
        "LICENCIADO EN DERECHO",
        "LICENCIADO EN EDUCACION",
        "LICENCIADO EN ENFERMERIA",
        "LICENCIADO EN PEDAGOGIA",
        "LICENCIADO EN PSICOLOGIA",
        "MAESTRO",
        "MEDICO GENERAL",
        "MEDICO ESPECIALISTA",
        "NUTRICIONISTA",
        "ODONTOLOGO",
        "PROFESOR",
        "PSICOLOGO",
        "QUIMICO",
        "TRABAJADOR SOCIAL",
        "VETERINARIO"
    ]
};

// Función helper para obtener profesiones de un sector
export const getProfesionesBySector = (sector: string): string[] => {
    if (sector in PROFESIONES_POR_SECTOR) {
        return PROFESIONES_POR_SECTOR[sector as SectorEconomico];
    }
    return [];
};